#!/bin/bash
# Simple BitchX starter

export UID=$(id -u)
export GID=$(id -g)

echo "Starting BitchX container..."
docker compose up -d

echo ""
echo "BitchX is starting!"
echo ""
echo "To attach to BitchX: ./bx-attach"
echo "To detach: Press Ctrl+P, Ctrl+Q"
echo ""
echo "Note: When you /quit BitchX, the container will stop."
echo "      Run this script again to restart."
