services:
  bitchx:
    build:
      context: .
      dockerfile: Dockerfile.simple
      args:
        USER_ID: ${UID:-1000}
        GROUP_ID: ${GID:-1000}
    image: bitchx-simple:local
    container_name: bitchx
    stdin_open: true
    tty: true
    restart: unless-stopped
    environment:
      - TERM=xterm-256color
    volumes:
      # BitchX config - persists settings
      - ./config/.BitchX:/home/mute/.BitchX
      # Osiris script - your customizations
      - ./osiris-config:/home/mute/osiris
      # IRC config - auto-loads script
      - ./config/.ircrc:/home/mute/.ircrc
      # EFnet-only server list
      - ./config/efnet-servers.list:/home/mute/efnet-servers.list
    # Keep container running, don't use startup.sh as entrypoint
    entrypoint: ["sleep", "infinity"]
